name: mi_arena
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  badges: ^2.0.3
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  carousel_slider : ^4.1.1
  dotted_border: ^2.0.0+2
  file_picker: ^4.5.1
  cloudinary_public: ^0.11.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
